# =========================================================
# General routing configuration
# =========================================================

app.routing.header-retailer-id=X-Retailer-Id
app.routing.header-state-id=X-State-Id
app.routing.header-state-code=X-State-Code

# =========================================================
# UP database
# =========================================================

app.state-databases[UP].state-id=9
app.state-databases[UP].state-code=UP
app.state-databases[UP].state-name=Uttar Pradesh

app.state-databases[UP].jdbc-url=jdbc:postgresql://10.246.45.19:5434/mFMS?currentSchema=mfms_up
app.state-databases[UP].username=postgres
app.state-databases[UP].password=postgres

app.state-databases[UP].minimum-idle=2
app.state-databases[UP].maximum-pool-size=30
app.state-databases[UP].connection-timeout=30000
app.state-databases[UP].validation-timeout=5000
app.state-databases[UP].idle-timeout=600000
app.state-databases[UP].max-lifetime=1800000
app.state-databases[UP].keepalive-time=300000

# =========================================================
# Haryana database
# =========================================================

app.state-databases[HR].state-id=6
app.state-databases[HR].state-code=HR
app.state-databases[HR].state-name=Haryana

app.state-databases[HR].jdbc-url=jdbc:postgresql://10.246.45.19:5434/mFMS?currentSchema=mfms_HR
app.state-databases[HR].username=postgres
app.state-databases[HR].password=postgres

app.state-databases[HR].minimum-idle=2
app.state-databases[HR].maximum-pool-size=15
app.state-databases[HR].connection-timeout=30000
app.state-databases[HR].validation-timeout=5000
app.state-databases[HR].idle-timeout=600000
app.state-databases[HR].max-lifetime=1800000
app.state-databases[HR].keepalive-time=300000

# =========================================================
# Maharashtra database
# =========================================================

app.state-databases[MH].state-id=27
app.state-databases[MH].state-code=MH
app.state-databases[MH].state-name=Maharashtra

app.state-databases[MH].jdbc-url=jdbc:postgresql://10.246.45.19:5434/mFMS?currentSchema=mfms_MH
app.state-databases[MH].username=postgres
app.state-databases[MH].password=postgres

app.state-databases[MH].minimum-idle=2
app.state-databases[MH].maximum-pool-size=20
app.state-databases[MH].connection-timeout=30000
app.state-databases[MH].validation-timeout=5000
app.state-databases[MH].idle-timeout=600000
app.state-databases[MH].max-lifetime=1800000
app.state-databases[MH].keepalive-time=300000
