app:
  routing:
    header-retailer-id: X-Retailer-Id
    header-state-id: X-State-Id
    header-state-code: X-State-Code

  default-database:
    jdbc-url: jdbc:postgresql://10.246.45.14:5432/ifms_master
    username: master_user
    password: ChangeThisPassword

    minimum-idle: 2
    maximum-pool-size: 10

    connection-timeout: 30000
    validation-timeout: 5000
    idle-timeout: 600000
    max-lifetime: 1800000
    keepalive-time: 300000

    retailer-lookup-sql: >-
      select
          state_id,
          state_short_name
      from mfms.connection_url_vw
      where dealer_id = ?
        

  state-databases:
    UP:
      state-id: 9
      state-code: UP
      state-name: Uttar Pradesh
      jdbc-url: jdbc:postgresql://10.10.20.9:5432/ifms_up
      username: up_user
      password: ChangeThisPassword
      minimum-idle: 2
      maximum-pool-size: 20

    MP:
      state-id: 23
      state-code: MP
      state-name: Madhya Pradesh
      jdbc-url: jdbc:postgresql://10.10.20.23:5432/ifms_mp
      username: mp_user
      password: ChangeThisPassword
      minimum-idle: 2
      maximum-pool-size: 20
